apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: <cluster_issuer_name>           # e.g., letsencrypt-prod
spec:
  acme:
    email: <your_email_address>         # e.g., your_mail_id@gmail.com
    server: <acme_server_url>           # e.g., https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: <private_key_secret_name>   # e.g., letsencrypt-prod-key
    solvers:
      - http01:
          ingress:
            class: <ingress_class>      # e.g., nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: <certificate_name>              # e.g., myapi-cert
  namespace: <namespace>                # e.g., default
spec:
  secretName: <tls_secret_name>         # e.g., myapi-tls
  issuerRef:
    name: <cluster_issuer_name>         # same as above
    kind: <issuer_kind>                 # e.g., ClusterIssuer
  commonName: <domain_name>             # e.g., myapi.servebeer.com
  dnsNames:
    - <domain_name>                     # same as above
